### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable in line 404 of OEPL-Flasher.py 

### ISSUE THREAD

**Issue by ohuf** [OpenEPaperLink/OpenEPaperLink#411]
**Describe the bug**
running the OPEPL flasher withattached Tag Flasher and Tag throws an error:

`python OEPL-Flasher.py -e -z -p COM8 read blaat.bin --flash --pt
Successfully opened serial port COM8
Connection with the flasher established. Version: 48
timeout waiting for reply
Traceback (most recent call last):
  File "C:\Users\ohuf\Documents\Code\OpenEPaperLink\Tag_Flasher\OEPL-Flasher.py", line 485, in <module>
    main()
  File "C:\Users\ohuf\Documents\Code\OpenEPaperLink\Tag_Flasher\OEPL-Flasher.py", line 404, in main
    if (answer[0] == 1):
        ~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable`


EDIT 1:
I compiled and uploaded the most recent version (50) of the ESP32 S2 Tag Flasher to the device.
The problem persists:
`Using external port
Successfully opened serial port COM8
Connection with the flasher established. Version: 50
timeout waiting for reply
Traceback (most recent call last):
  File "C:\Users\oli\Documents\Code\OpenEPaperLink\Tag_Flasher\OEPL-Flasher.py", line 485, in <module>
    main()
  File "C:\Users\oli\Documents\Code\OpenEPaperLink\Tag_Flasher\OEPL-Flasher.py", line 404, in main
    if (answer[0] == 1):
        ~~~~~~^^^`

**To Reproduce**
Steps to reproduce the behavior:
1. Connect the Tag to the flasher
2. Connect Flasher to USB Port
3. evaluate the associated COM Port
4. run the command above

**Expected behavior**
OEPL-Flasher should read the flash


**Additional context**
I tried this with python 3.11 as well as the latest 3.12 : same behaviour amongst the two.

**Comment by ohuf** [comment]
OK, this seems to happen only, when the flasher (ESP32-S2) has bad contact to the tag.
I checked my adapter and one of the pogo-pins wouldn't pogo anymore. 
Replaced the pin in question and now I can read the flash!
